### ISSUE TITLE
Realtime YAML builder. 

### ISSUE THREAD

**Issue by orta** [Keithbsmiley/color-builder#1]
Go copy http://cocoadocs.org/readme/

**Comment by keith** [comment]
Lol wut?

**Comment by orta** [comment]
likely was based on a conversation at the time, but I guess it was "add support for choosing a colour based on a GUI, 

![screen shot 2016-02-28 at 08 26 52](https://cloud.githubusercontent.com/assets/49038/13379501/18b96400-ddf5-11e5-9e13-d6cb59a48a9a.png)
